### ISSUE TITLE
Unexpected error Attribute 'to_json' is deprecated

### ISSUE THREAD

**Issue by karthickdm** [rickypc/robotframework-extendedrequestslibrary#6]
I installed latest version Robotframework 3.2.1 and ExtendedRequestedLibrary is not compatible with the latest version and getting Attribute 'to_json' is deprecated

Could you please resolve this issue asap.

 [ ERROR ] Unexpected error: AttributeError: 'to_json' is deprecated.
 Traceback (most recent call last):
   File "/usr/local/lib/python3.6/site-packages/robot/utils/application.py", line 83, in _execute
     rc = self.main(arguments, **options)
   File "/usr/local/lib/python3.6/site-packages/robot/run.py", line 443, in main
     result = suite.run(settings)
   File "/usr/local/lib/python3.6/site-packages/robot/running/model.py", line 259, in run
     self.visit(runner)
   File "/usr/local/lib/python3.6/site-packages/robot/model/testsuite.py", line 174, in visit
     visitor.visit_suite(self)
   File "/usr/local/lib/python3.6/site-packages/robot/model/visitor.py", line 87, in visit_suite
     suite.suites.visit(self)
   File "/usr/local/lib/python3.6/site-packages/robot/model/itemlist.py", line 77, in visit
     item.visit(visitor)
   File "/usr/local/lib/python3.6/site-packages/robot/model/testsuite.py", line 174, in visit
     visitor.visit_suite(self)
   File "/usr/local/lib/python3.6/site-packages/robot/model/visitor.py", line 85, in visit_suite
     if self.start_suite(suite) is not False:
   File "/usr/local/lib/python3.6/site-packages/robot/running/runner.py", line 74, in start_suite
     ns.handle_imports()
   File "/usr/local/lib/python3.6/site-packages/robot/running/namespace.py", line 55, in handle_imports
     self._handle_imports(self._imports)
   File "/usr/local/lib/python3.6/site-packages/robot/running/namespace.py", line 66, in _handle_imports
     self._import(item)
   File "/usr/local/lib/python3.6/site-packages/robot/running/namespace.py", line 74, in _import
     action(import_setting)
   File "/usr/local/lib/python3.6/site-packages/robot/running/namespace.py", line 87, in _import_resource
     self._handle_imports(resource.imports)
   File "/usr/local/lib/python3.6/site-packages/robot/running/namespace.py", line 66, in _handle_imports
     self._import(item)
   File "/usr/local/lib/python3.6/site-packages/robot/running/namespace.py", line 74, in _import
     action(import_setting)
   File "/usr/local/lib/python3.6/site-packages/robot/running/namespace.py", line 128, in _import_library
     import_setting.alias, self.variables)
   File "/usr/local/lib/python3.6/site-packages/robot/running/importer.py", line 48, in import_library
     lib = self._import_library(name, positional, named, lib)
   File "/usr/local/lib/python3.6/site-packages/robot/running/importer.py", line 78, in _import_library
     lib.create_handlers()
   File "/usr/local/lib/python3.6/site-packages/robot/running/testlibraries.py", line 111, in create_handlers
     self._create_handlers(self.get_instance())
   File "/usr/local/lib/python3.6/site-packages/robot/running/testlibraries.py", line 243, in _create_handlers
     method = self._try_to_get_handler_method(libcode, name)
   File "/usr/local/lib/python3.6/site-packages/robot/running/testlibraries.py", line 271, in _try_to_get_handler_method
     return self._get_handler_method(libcode, name)
   File "/usr/local/lib/python3.6/site-packages/robot/running/testlibraries.py", line 350, in _get_handler_method
     return getattr(libinst, name)
   File "/usr/local/lib/python3.6/site-packages/ExtendedRequestsLibrary/__init__.py", line 111, in __getattribute__
     raise AttributeError("'%s' is deprecated." % name)

**Comment by karthickdm** [comment]
@rickypc : Can you please take a look at this issue ?

**Comment by apple314159** [comment]
Just ran into the same problem. As a work around I removed 'to_json' from the list in line 110 of
https://github.com/rickypc/robotframework-extendedrequestslibrary/blob/master/src/ExtendedRequestsLibrary/__init__.py

**Comment by rruckley** [comment]
Raised PR #8 to implement fix suggested by @apple314159

**Comment by hlong24399** [comment]
Can someone please merge #8 to fix this!
